GET http://localhost:9000/get
Content-Type: application/json

{
    
}
#####

POST http://localhost:9000/add
Content-Type: application/json

{
    "Name": "namebeer",
    "Type": "typebeer",
    "Detail": "detailbeer",
    "Url": "https://example.com/url.jpg",
    "User": "woraopon asavanik"
}
###############
POST http://localhost:9000/add
Content-Type: application/json

{
    "Name": "999",
    "User": "woraopon asavanik"
}
###############
PUT http://localhost:9000/update/5
Content-Type: application/json

{
    "Name": "1",
    "Type": "1",
    "Detail": "1",
    "Url": "1",
    "User": "worapon asavanik",
    "Idrm": "5"
  
}
####
PUT http://localhost:9000/update/5
Content-Type: application/json

{
    "Name": "bank",
    "Type": "bank3",
    "User": "worapon asavanik",
    "Idrm": "5"
  
}
#######
PUT http://localhost:9000/update/87
Content-Type: application/json

{
    "Type": "87",
    "Detail": "87",
    "Url": "87",
    "User": "worapon asavanik",
    "Idrm": "87"
  
}
####
DELETE http://localhost:9000/delete/13
Content-Type: application/json
{
    "ID": 13,
   "Name": "worapon asavanik"
}